/* Autogenerated by mlir-tblgen; don't manually edit. */

package org.seqra.ir.api.cir.cfg

enum class CIRAsmFlavor {
    X86Att, X86Intel,
}

enum class CIRAtomicFetchKind {
    Add, Sub, And, Xor, Or, Nand, Max, Min,
}

enum class CIRAwaitKind {
    Init, User, Yield, Final,
}

enum class CIRBinOpKind {
    Mul, Div, Rem, Add, Sub, And, Xor, Or,
}

enum class CIRBinOpOverflowKind {
    Add, Sub, Mul,
}

enum class CIRCallingConv {
    C, SpirKernel, SpirFunction,
}

enum class CIRCaseOpKind {
    Default, Equal, Anyof, Range,
}

enum class CIRCastKind {
    IntToBool, ArrayToPtrdecay, Integral, Bitcast, Floating, PtrToBool, FloatToInt, IntToPtr, PtrToInt, FloatToBool, BoolToInt, IntToFloat, BoolToFloat, AddressSpace, FloatToComplex, IntToComplex, FloatComplexToReal, IntComplexToReal, FloatComplexToBool, IntComplexToBool, FloatComplex, FloatComplexToIntComplex, IntComplex, IntComplexToFloatComplex,
}

enum class CIRCatchParamKind {
    Begin, End,
}

enum class CIRCmpOpKind {
    Lt, Le, Gt, Ge, Eq, Ne,
}

enum class CIRCmpOrdering {
    Strong, Partial,
}

enum class CIRComplexBinOpKind {
    Mul, Div,
}

enum class CIRComplexRangeKind {
    Full, Improved, Promoted, Basic, None,
}

enum class CIRDynamicCastKind {
    Ptr, Ref,
}

enum class CIRGlobalLinkageKind {
    ExternalLinkage, AvailableExternallyLinkage, LinkOnceAnyLinkage, LinkOnceODRLinkage, WeakAnyLinkage, WeakODRLinkage, InternalLinkage, PrivateLinkage, ExternalWeakLinkage, CommonLinkage,
}

enum class CIRInlineKind {
    NoInline, AlwaysInline, InlineHint,
}

enum class CIRMemOrder {
    Relaxed, Consume, Acquire, Release, AcquireRelease, SequentiallyConsistent,
}

enum class CIRSignedOverflowBehavior {
    Undefined, Defined, Trapping,
}

enum class CIRSizeInfoType {
    Min, Max,
}

enum class CIRSourceLanguage {
    C, CXX, OpenCLC,
}

enum class CIRTLSModel {
    GeneralDynamic, LocalDynamic, InitialExec, LocalExec,
}

enum class CIRUnaryOpKind {
    Inc, Dec, Plus, Minus, Not,
}

enum class CIRVisibilityKind {
    Default, Hidden, Protected,
}

enum class CIRRecordKind {
    Class, Union, Struct,
}

enum class MLIRSignednessSemantics {
    Signless, Signed, Unsigned,
}
