/* Autogenerated by mlir-tblgen; don't manually edit. */

package org.seqra.ir.impl.cfg.builder

import org.seqra.ir.api.cir.cfg.*
import org.seqra.ir.impl.grpc.Enum

fun buildCIRAsmFlavor(enum : Enum.CIRAsmFlavor) = when (enum) {
    Enum.CIRAsmFlavor.AsmFlavor_X86Att -> CIRAsmFlavor.X86Att
    Enum.CIRAsmFlavor.AsmFlavor_X86Intel -> CIRAsmFlavor.X86Intel
    Enum.CIRAsmFlavor.UNRECOGNIZED -> throw Exception()
}

fun buildCIRAtomicFetchKind(enum : Enum.CIRAtomicFetchKind) = when (enum) {
    Enum.CIRAtomicFetchKind.AtomicFetchKind_Add -> CIRAtomicFetchKind.Add
    Enum.CIRAtomicFetchKind.AtomicFetchKind_Sub -> CIRAtomicFetchKind.Sub
    Enum.CIRAtomicFetchKind.AtomicFetchKind_And -> CIRAtomicFetchKind.And
    Enum.CIRAtomicFetchKind.AtomicFetchKind_Xor -> CIRAtomicFetchKind.Xor
    Enum.CIRAtomicFetchKind.AtomicFetchKind_Or -> CIRAtomicFetchKind.Or
    Enum.CIRAtomicFetchKind.AtomicFetchKind_Nand -> CIRAtomicFetchKind.Nand
    Enum.CIRAtomicFetchKind.AtomicFetchKind_Max -> CIRAtomicFetchKind.Max
    Enum.CIRAtomicFetchKind.AtomicFetchKind_Min -> CIRAtomicFetchKind.Min
    Enum.CIRAtomicFetchKind.UNRECOGNIZED -> throw Exception()
}

fun buildCIRAwaitKind(enum : Enum.CIRAwaitKind) = when (enum) {
    Enum.CIRAwaitKind.AwaitKind_Init -> CIRAwaitKind.Init
    Enum.CIRAwaitKind.AwaitKind_User -> CIRAwaitKind.User
    Enum.CIRAwaitKind.AwaitKind_Yield -> CIRAwaitKind.Yield
    Enum.CIRAwaitKind.AwaitKind_Final -> CIRAwaitKind.Final
    Enum.CIRAwaitKind.UNRECOGNIZED -> throw Exception()
}

fun buildCIRBinOpKind(enum : Enum.CIRBinOpKind) = when (enum) {
    Enum.CIRBinOpKind.BinOpKind_Mul -> CIRBinOpKind.Mul
    Enum.CIRBinOpKind.BinOpKind_Div -> CIRBinOpKind.Div
    Enum.CIRBinOpKind.BinOpKind_Rem -> CIRBinOpKind.Rem
    Enum.CIRBinOpKind.BinOpKind_Add -> CIRBinOpKind.Add
    Enum.CIRBinOpKind.BinOpKind_Sub -> CIRBinOpKind.Sub
    Enum.CIRBinOpKind.BinOpKind_And -> CIRBinOpKind.And
    Enum.CIRBinOpKind.BinOpKind_Xor -> CIRBinOpKind.Xor
    Enum.CIRBinOpKind.BinOpKind_Or -> CIRBinOpKind.Or
    Enum.CIRBinOpKind.UNRECOGNIZED -> throw Exception()
}

fun buildCIRBinOpOverflowKind(enum : Enum.CIRBinOpOverflowKind) = when (enum) {
    Enum.CIRBinOpOverflowKind.BinOpOverflowKind_Add -> CIRBinOpOverflowKind.Add
    Enum.CIRBinOpOverflowKind.BinOpOverflowKind_Sub -> CIRBinOpOverflowKind.Sub
    Enum.CIRBinOpOverflowKind.BinOpOverflowKind_Mul -> CIRBinOpOverflowKind.Mul
    Enum.CIRBinOpOverflowKind.UNRECOGNIZED -> throw Exception()
}

fun buildCIRCallingConv(enum : Enum.CIRCallingConv) = when (enum) {
    Enum.CIRCallingConv.CallingConv_C -> CIRCallingConv.C
    Enum.CIRCallingConv.CallingConv_SpirKernel -> CIRCallingConv.SpirKernel
    Enum.CIRCallingConv.CallingConv_SpirFunction -> CIRCallingConv.SpirFunction
    Enum.CIRCallingConv.UNRECOGNIZED -> throw Exception()
}

fun buildCIRCaseOpKind(enum : Enum.CIRCaseOpKind) = when (enum) {
    Enum.CIRCaseOpKind.CaseOpKind_Default -> CIRCaseOpKind.Default
    Enum.CIRCaseOpKind.CaseOpKind_Equal -> CIRCaseOpKind.Equal
    Enum.CIRCaseOpKind.CaseOpKind_Anyof -> CIRCaseOpKind.Anyof
    Enum.CIRCaseOpKind.CaseOpKind_Range -> CIRCaseOpKind.Range
    Enum.CIRCaseOpKind.UNRECOGNIZED -> throw Exception()
}

fun buildCIRCastKind(enum : Enum.CIRCastKind) = when (enum) {
    Enum.CIRCastKind.CastKind_IntToBool -> CIRCastKind.IntToBool
    Enum.CIRCastKind.CastKind_ArrayToPtrdecay -> CIRCastKind.ArrayToPtrdecay
    Enum.CIRCastKind.CastKind_Integral -> CIRCastKind.Integral
    Enum.CIRCastKind.CastKind_Bitcast -> CIRCastKind.Bitcast
    Enum.CIRCastKind.CastKind_Floating -> CIRCastKind.Floating
    Enum.CIRCastKind.CastKind_PtrToBool -> CIRCastKind.PtrToBool
    Enum.CIRCastKind.CastKind_FloatToInt -> CIRCastKind.FloatToInt
    Enum.CIRCastKind.CastKind_IntToPtr -> CIRCastKind.IntToPtr
    Enum.CIRCastKind.CastKind_PtrToInt -> CIRCastKind.PtrToInt
    Enum.CIRCastKind.CastKind_FloatToBool -> CIRCastKind.FloatToBool
    Enum.CIRCastKind.CastKind_BoolToInt -> CIRCastKind.BoolToInt
    Enum.CIRCastKind.CastKind_IntToFloat -> CIRCastKind.IntToFloat
    Enum.CIRCastKind.CastKind_BoolToFloat -> CIRCastKind.BoolToFloat
    Enum.CIRCastKind.CastKind_AddressSpace -> CIRCastKind.AddressSpace
    Enum.CIRCastKind.CastKind_FloatToComplex -> CIRCastKind.FloatToComplex
    Enum.CIRCastKind.CastKind_IntToComplex -> CIRCastKind.IntToComplex
    Enum.CIRCastKind.CastKind_FloatComplexToReal -> CIRCastKind.FloatComplexToReal
    Enum.CIRCastKind.CastKind_IntComplexToReal -> CIRCastKind.IntComplexToReal
    Enum.CIRCastKind.CastKind_FloatComplexToBool -> CIRCastKind.FloatComplexToBool
    Enum.CIRCastKind.CastKind_IntComplexToBool -> CIRCastKind.IntComplexToBool
    Enum.CIRCastKind.CastKind_FloatComplex -> CIRCastKind.FloatComplex
    Enum.CIRCastKind.CastKind_FloatComplexToIntComplex -> CIRCastKind.FloatComplexToIntComplex
    Enum.CIRCastKind.CastKind_IntComplex -> CIRCastKind.IntComplex
    Enum.CIRCastKind.CastKind_IntComplexToFloatComplex -> CIRCastKind.IntComplexToFloatComplex
    Enum.CIRCastKind.UNRECOGNIZED -> throw Exception()
}

fun buildCIRCatchParamKind(enum : Enum.CIRCatchParamKind) = when (enum) {
    Enum.CIRCatchParamKind.CatchParamKind_Begin -> CIRCatchParamKind.Begin
    Enum.CIRCatchParamKind.CatchParamKind_End -> CIRCatchParamKind.End
    Enum.CIRCatchParamKind.UNRECOGNIZED -> throw Exception()
}

fun buildCIRCmpOpKind(enum : Enum.CIRCmpOpKind) = when (enum) {
    Enum.CIRCmpOpKind.CmpOpKind_Lt -> CIRCmpOpKind.Lt
    Enum.CIRCmpOpKind.CmpOpKind_Le -> CIRCmpOpKind.Le
    Enum.CIRCmpOpKind.CmpOpKind_Gt -> CIRCmpOpKind.Gt
    Enum.CIRCmpOpKind.CmpOpKind_Ge -> CIRCmpOpKind.Ge
    Enum.CIRCmpOpKind.CmpOpKind_Eq -> CIRCmpOpKind.Eq
    Enum.CIRCmpOpKind.CmpOpKind_Ne -> CIRCmpOpKind.Ne
    Enum.CIRCmpOpKind.UNRECOGNIZED -> throw Exception()
}

fun buildCIRCmpOrdering(enum : Enum.CIRCmpOrdering) = when (enum) {
    Enum.CIRCmpOrdering.CmpOrdering_Strong -> CIRCmpOrdering.Strong
    Enum.CIRCmpOrdering.CmpOrdering_Partial -> CIRCmpOrdering.Partial
    Enum.CIRCmpOrdering.UNRECOGNIZED -> throw Exception()
}

fun buildCIRComplexBinOpKind(enum : Enum.CIRComplexBinOpKind) = when (enum) {
    Enum.CIRComplexBinOpKind.ComplexBinOpKind_Mul -> CIRComplexBinOpKind.Mul
    Enum.CIRComplexBinOpKind.ComplexBinOpKind_Div -> CIRComplexBinOpKind.Div
    Enum.CIRComplexBinOpKind.UNRECOGNIZED -> throw Exception()
}

fun buildCIRComplexRangeKind(enum : Enum.CIRComplexRangeKind) = when (enum) {
    Enum.CIRComplexRangeKind.ComplexRangeKind_Full -> CIRComplexRangeKind.Full
    Enum.CIRComplexRangeKind.ComplexRangeKind_Improved -> CIRComplexRangeKind.Improved
    Enum.CIRComplexRangeKind.ComplexRangeKind_Promoted -> CIRComplexRangeKind.Promoted
    Enum.CIRComplexRangeKind.ComplexRangeKind_Basic -> CIRComplexRangeKind.Basic
    Enum.CIRComplexRangeKind.ComplexRangeKind_None -> CIRComplexRangeKind.None
    Enum.CIRComplexRangeKind.UNRECOGNIZED -> throw Exception()
}

fun buildCIRDynamicCastKind(enum : Enum.CIRDynamicCastKind) = when (enum) {
    Enum.CIRDynamicCastKind.DynamicCastKind_Ptr -> CIRDynamicCastKind.Ptr
    Enum.CIRDynamicCastKind.DynamicCastKind_Ref -> CIRDynamicCastKind.Ref
    Enum.CIRDynamicCastKind.UNRECOGNIZED -> throw Exception()
}

fun buildCIRGlobalLinkageKind(enum : Enum.CIRGlobalLinkageKind) = when (enum) {
    Enum.CIRGlobalLinkageKind.GlobalLinkageKind_ExternalLinkage -> CIRGlobalLinkageKind.ExternalLinkage
    Enum.CIRGlobalLinkageKind.GlobalLinkageKind_AvailableExternallyLinkage -> CIRGlobalLinkageKind.AvailableExternallyLinkage
    Enum.CIRGlobalLinkageKind.GlobalLinkageKind_LinkOnceAnyLinkage -> CIRGlobalLinkageKind.LinkOnceAnyLinkage
    Enum.CIRGlobalLinkageKind.GlobalLinkageKind_LinkOnceODRLinkage -> CIRGlobalLinkageKind.LinkOnceODRLinkage
    Enum.CIRGlobalLinkageKind.GlobalLinkageKind_WeakAnyLinkage -> CIRGlobalLinkageKind.WeakAnyLinkage
    Enum.CIRGlobalLinkageKind.GlobalLinkageKind_WeakODRLinkage -> CIRGlobalLinkageKind.WeakODRLinkage
    Enum.CIRGlobalLinkageKind.GlobalLinkageKind_InternalLinkage -> CIRGlobalLinkageKind.InternalLinkage
    Enum.CIRGlobalLinkageKind.GlobalLinkageKind_PrivateLinkage -> CIRGlobalLinkageKind.PrivateLinkage
    Enum.CIRGlobalLinkageKind.GlobalLinkageKind_ExternalWeakLinkage -> CIRGlobalLinkageKind.ExternalWeakLinkage
    Enum.CIRGlobalLinkageKind.GlobalLinkageKind_CommonLinkage -> CIRGlobalLinkageKind.CommonLinkage
    Enum.CIRGlobalLinkageKind.UNRECOGNIZED -> throw Exception()
}

fun buildCIRInlineKind(enum : Enum.CIRInlineKind) = when (enum) {
    Enum.CIRInlineKind.InlineKind_NoInline -> CIRInlineKind.NoInline
    Enum.CIRInlineKind.InlineKind_AlwaysInline -> CIRInlineKind.AlwaysInline
    Enum.CIRInlineKind.InlineKind_InlineHint -> CIRInlineKind.InlineHint
    Enum.CIRInlineKind.UNRECOGNIZED -> throw Exception()
}

fun buildCIRMemOrder(enum : Enum.CIRMemOrder) = when (enum) {
    Enum.CIRMemOrder.MemOrder_Relaxed -> CIRMemOrder.Relaxed
    Enum.CIRMemOrder.MemOrder_Consume -> CIRMemOrder.Consume
    Enum.CIRMemOrder.MemOrder_Acquire -> CIRMemOrder.Acquire
    Enum.CIRMemOrder.MemOrder_Release -> CIRMemOrder.Release
    Enum.CIRMemOrder.MemOrder_AcquireRelease -> CIRMemOrder.AcquireRelease
    Enum.CIRMemOrder.MemOrder_SequentiallyConsistent -> CIRMemOrder.SequentiallyConsistent
    Enum.CIRMemOrder.UNRECOGNIZED -> throw Exception()
}

fun buildCIRSignedOverflowBehavior(enum : Enum.CIRSignedOverflowBehavior) = when (enum) {
    Enum.CIRSignedOverflowBehavior.SignedOverflowBehavior_Undefined -> CIRSignedOverflowBehavior.Undefined
    Enum.CIRSignedOverflowBehavior.SignedOverflowBehavior_Defined -> CIRSignedOverflowBehavior.Defined
    Enum.CIRSignedOverflowBehavior.SignedOverflowBehavior_Trapping -> CIRSignedOverflowBehavior.Trapping
    Enum.CIRSignedOverflowBehavior.UNRECOGNIZED -> throw Exception()
}

fun buildCIRSizeInfoType(enum : Enum.CIRSizeInfoType) = when (enum) {
    Enum.CIRSizeInfoType.SizeInfoType_Min -> CIRSizeInfoType.Min
    Enum.CIRSizeInfoType.SizeInfoType_Max -> CIRSizeInfoType.Max
    Enum.CIRSizeInfoType.UNRECOGNIZED -> throw Exception()
}

fun buildCIRSourceLanguage(enum : Enum.CIRSourceLanguage) = when (enum) {
    Enum.CIRSourceLanguage.SourceLanguage_C -> CIRSourceLanguage.C
    Enum.CIRSourceLanguage.SourceLanguage_CXX -> CIRSourceLanguage.CXX
    Enum.CIRSourceLanguage.SourceLanguage_OpenCLC -> CIRSourceLanguage.OpenCLC
    Enum.CIRSourceLanguage.UNRECOGNIZED -> throw Exception()
}

fun buildCIRTLSModel(enum : Enum.CIRTLSModel) = when (enum) {
    Enum.CIRTLSModel.TLSModel_GeneralDynamic -> CIRTLSModel.GeneralDynamic
    Enum.CIRTLSModel.TLSModel_LocalDynamic -> CIRTLSModel.LocalDynamic
    Enum.CIRTLSModel.TLSModel_InitialExec -> CIRTLSModel.InitialExec
    Enum.CIRTLSModel.TLSModel_LocalExec -> CIRTLSModel.LocalExec
    Enum.CIRTLSModel.UNRECOGNIZED -> throw Exception()
}

fun buildCIRUnaryOpKind(enum : Enum.CIRUnaryOpKind) = when (enum) {
    Enum.CIRUnaryOpKind.UnaryOpKind_Inc -> CIRUnaryOpKind.Inc
    Enum.CIRUnaryOpKind.UnaryOpKind_Dec -> CIRUnaryOpKind.Dec
    Enum.CIRUnaryOpKind.UnaryOpKind_Plus -> CIRUnaryOpKind.Plus
    Enum.CIRUnaryOpKind.UnaryOpKind_Minus -> CIRUnaryOpKind.Minus
    Enum.CIRUnaryOpKind.UnaryOpKind_Not -> CIRUnaryOpKind.Not
    Enum.CIRUnaryOpKind.UNRECOGNIZED -> throw Exception()
}

fun buildCIRVisibilityKind(enum : Enum.CIRVisibilityKind) = when (enum) {
    Enum.CIRVisibilityKind.VisibilityKind_Default -> CIRVisibilityKind.Default
    Enum.CIRVisibilityKind.VisibilityKind_Hidden -> CIRVisibilityKind.Hidden
    Enum.CIRVisibilityKind.VisibilityKind_Protected -> CIRVisibilityKind.Protected
    Enum.CIRVisibilityKind.UNRECOGNIZED -> throw Exception()
}

fun buildCIRRecordKind(enum : Enum.CIRRecordKind) = when (enum) {
    Enum.CIRRecordKind.CIRRecordKind_Class -> CIRRecordKind.Class
    Enum.CIRRecordKind.CIRRecordKind_Union -> CIRRecordKind.Union
    Enum.CIRRecordKind.CIRRecordKind_Struct -> CIRRecordKind.Struct
    Enum.CIRRecordKind.UNRECOGNIZED -> throw Exception()
}

fun buildMLIRSignednessSemantics(enum : Enum.MLIRSignednessSemantics) = when (enum) {
    Enum.MLIRSignednessSemantics.MLIRSignednessSemantics_Signless -> MLIRSignednessSemantics.Signless
    Enum.MLIRSignednessSemantics.MLIRSignednessSemantics_Signed -> MLIRSignednessSemantics.Signed
    Enum.MLIRSignednessSemantics.MLIRSignednessSemantics_Unsigned -> MLIRSignednessSemantics.Unsigned
    Enum.MLIRSignednessSemantics.UNRECOGNIZED -> throw Exception()
}
